export const signatures: Record<string, string> = {
  IF: "logical_test, value_if_true, [value_if_false]",
  IFERROR: "value, value_if_error",
  IFNA: "value, value_if_na",
  IFS: "logical_test1, value1, ...",
  SWITCH: "expression, value1, result1, ..., [default]",
  CHOOSE: "index_num, value1, ...",
  ROUND: "number, num_digits",
  ROUNDUP: "number, num_digits",
  ROUNDDOWN: "number, num_digits",
  TRUNC: "number, [num_digits]",
  POWER: "number, power",
  ATAN2: "x_num, y_num",
  LOG: "number, [base]",
  MOD: "number, divisor",
  QUOTIENT: "numerator, denominator",
  MROUND: "number, multiple",
  "CEILING.MATH": "number, [significance], [mode]",
  "FLOOR.MATH": "number, [significance], [mode]",
  RANDBETWEEN: "bottom, top",
  COMBIN: "number, number_chosen",
  LARGE: "array, k",
  SMALL: "array, k",
  "PERCENTILE.INC": "array, k",
  "QUARTILE.INC": "array, quart",
  "RANK.EQ": "number, ref, [order]",
  SUMIF: "range, criteria, [sum_range]",
  SUMIFS: "sum_range, criteria_range1, criteria1, ...",
  COUNTIF: "range, criteria",
  COUNTIFS: "criteria_range1, criteria1, ...",
  AVERAGEIF: "range, criteria, [average_range]",
  AVERAGEIFS: "average_range, criteria_range1, criteria1, ...",
  SUMPRODUCT: "array1, [array2], ...",
  CORREL: "array1, array2",
  "COVARIANCE.P": "array1, array2",
  "COVARIANCE.S": "array1, array2",
  SLOPE: "known_ys, known_xs",
  INTERCEPT: "known_ys, known_xs",
  RSQ: "known_ys, known_xs",
  LEFT: "text, [num_chars]",
  RIGHT: "text, [num_chars]",
  MID: "text, start_num, num_chars",
  FIND: "find_text, within_text, [start_num]",
  SEARCH: "find_text, within_text, [start_num]",
  REPLACE: "old_text, start_num, num_chars, new_text",
  SUBSTITUTE: "text, old_text, new_text, [instance_num]",
  REPT: "text, number_times",
  CONCAT: "text1, ...",
  TEXTJOIN: "delimiter, ignore_empty, text1, ...",
  EXACT: "text1, text2",
  NUMBERVALUE: "text, [decimal_separator], [group_separator]",
  TEXT: "value, format_text",
  FIXED: "number, [decimals], [no_commas]",
  DATE: "year, month, day",
  TIME: "hour, minute, second",
  DAYS: "end_date, start_date",
  WEEKDAY: "serial_number, [return_type]",
  WEEKNUM: "serial_number, [return_type]",
  EDATE: "start_date, months",
  EOMONTH: "start_date, months",
  NETWORKDAYS: "start_date, end_date, [holidays]",
  WORKDAY: "start_date, days, [holidays]",
  DAYS360: "start_date, end_date, [method]",
  ROW: "[reference]",
  COLUMN: "[reference]",
  ROWS: "array",
  COLUMNS: "array",
  ADDRESS: "row_num, column_num, [abs_num], [a1], [sheet_text]",
  INDEX: "array, row_num, [column_num]",
  MATCH: "lookup_value, lookup_array, [match_type]",
  XMATCH: "lookup_value, lookup_array, [match_mode], [search_mode]",
  XLOOKUP:
    "lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode]",
  VLOOKUP: "lookup_value, table_array, col_index_num, [range_lookup]",
  HLOOKUP: "lookup_value, table_array, row_index_num, [range_lookup]",
  SEQUENCE: "rows, [columns], [start], [step]",
  TRANSPOSE: "array",
  FILTER: "array, include, [if_empty]",
  SORT: "array, [sort_index], [sort_order], [by_col]",
  SORTBY: "array, by_array1, [sort_order1], ...",
  UNIQUE: "array, [by_col], [exactly_once]",
  TAKE: "array, rows, [columns]",
  DROP: "array, rows, [columns]",
  CHOOSECOLS: "array, col_num1, ...",
  CHOOSEROWS: "array, row_num1, ...",
  VSTACK: "array1, ...",
  HSTACK: "array1, ...",
  PMT: "rate, nper, pv, [fv], [type]",
  FV: "rate, nper, pmt, [pv], [type]",
  PV: "rate, nper, pmt, [fv], [type]",
  NPER: "rate, pmt, pv, [fv], [type]",
  NPV: "rate, value1, ...",
  IRR: "values, [guess]",
  XNPV: "rate, values, dates",
  XIRR: "values, dates, [guess]",
  RATE: "nper, pmt, pv, [fv], [type], [guess]",
  SLN: "cost, salvage, life",
  SYD: "cost, salvage, life, per",
  EFFECT: "nominal_rate, npery",
  NOMINAL: "effect_rate, npery",
};
